name: ItemRecycle
version: '${project.version}'
main: com.linruo.ItemRecycle
commands:
  itemrecycle:
    description: " "
    aliases: ir
    permission: itemrecycle.use

#  reload:
#    description: " "
#    usage: ""
#    permission: itemrecycle.reload
#
permissions:
  itemrectcle.use:
    description: 使用权限
    default: op



